/**
 * Type declarations for the virtual:platform-docs module
 *
 * This module is generated by vite-plugin-platform-docs at build time
 * and contains all platform documentation bundled with the app.
 */

declare module 'virtual:platform-docs' {
  export interface PlatformDoc {
    /** Unique identifier derived from file path */
    id: string;
    /** Human-readable title extracted from H1 or filename */
    title: string;
    /** Original file path relative to project root */
    path: string;
    /** Category for grouping (getting-started, user-guides, product) */
    category: string;
    /** Sort order within category */
    order: number;
    /** Raw markdown content */
    content: string;
  }

  export type PlatformDocMeta = Omit<PlatformDoc, 'content'>;

  /** All platform docs with full content */
  export const platformDocs: PlatformDoc[];

  /** Platform docs metadata (without content) for sidebar listing */
  export const platformDocsMeta: PlatformDocMeta[];

  /** Get a single platform doc by ID */
  export function getPlatformDoc(id: string): PlatformDoc | undefined;

  /** Get all platform docs in a category */
  export function getPlatformDocsByCategory(category: string): PlatformDoc[];

  export default platformDocs;
}
